services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: urlshortner
      POSTGRES_USER: urlshortner
      POSTGRES_PASSWORD: urlshortner
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres:5432/urlshortner
      DB_USERNAME: urlshortner
      DB_PASSWORD: urlshortner
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  postgres-data:
